name: generate password

on: 
  workflow_dispatch:

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: msshashank1997/workflow
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.OUTPUT_PATH }}

    - name: Hello World
      run: python ${{ env.OUTPUT_PATH }}/secreate.py
      shell: sh
