name: Password generator
on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the action on
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace '3.x' with the Python version you need

      - name: Run Python Script
        run: python replace.py  # Replace '/path/to/your_script.py' with the actual path to your Python script
